{
  "comments": [
    {
      "key": {
        "uuid": "9bbbe3f1_b22130e2",
        "filename": "tests/__cxa_thread_atexit_test.cpp",
        "patchSetId": 5
      },
      "lineNbr": 57,
      "author": {
        "id": 1041673
      },
      "writtenOn": "2015-11-26T02:16:22Z",
      "side": 1,
      "message": "maybe just fail unconditionally here? this is something that is going to be fixed not something \"just the way it is\"",
      "revId": "6a12eb0392e73b6d2b0ac3308466b49d608aa840",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1be45325_8c59673f",
        "filename": "tests/__cxa_thread_atexit_test.cpp",
        "patchSetId": 5
      },
      "lineNbr": 57,
      "author": {
        "id": 1052399
      },
      "writtenOn": "2015-11-30T18:26:39Z",
      "side": 1,
      "message": "Yes, it should be fixed. Before it is fixed, is there a way to mark it as expected failure? I just want to avoid blocking other tests.",
      "parentUuid": "9bbbe3f1_b22130e2",
      "revId": "6a12eb0392e73b6d2b0ac3308466b49d608aa840",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "bb1267d6_29170d31",
        "filename": "tests/__cxa_thread_atexit_test.cpp",
        "patchSetId": 5
      },
      "lineNbr": 57,
      "author": {
        "id": 1003224
      },
      "writtenOn": "2015-11-30T18:37:10Z",
      "side": 1,
      "message": "we don\u0027t have any mechanism for expected failures. maybe this is the most reasonable thing for us to do. we should add the bug to the log output though, to make it easier for people to check on the status.",
      "parentUuid": "1be45325_8c59673f",
      "revId": "6a12eb0392e73b6d2b0ac3308466b49d608aa840",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "3bd59733_2d170d31",
        "filename": "tests/__cxa_thread_atexit_test.cpp",
        "patchSetId": 5
      },
      "lineNbr": 57,
      "author": {
        "id": 1052399
      },
      "writtenOn": "2015-11-30T18:58:00Z",
      "side": 1,
      "message": "Done",
      "parentUuid": "bb1267d6_29170d31",
      "revId": "6a12eb0392e73b6d2b0ac3308466b49d608aa840",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "9b0923b2_c8698fa2",
        "filename": "tests/__cxa_thread_atexit_test.cpp",
        "patchSetId": 5
      },
      "lineNbr": 57,
      "author": {
        "id": 1041673
      },
      "writtenOn": "2015-11-30T19:01:59Z",
      "side": 1,
      "message": "a test failure does not block other tests...",
      "parentUuid": "1be45325_8c59673f",
      "revId": "6a12eb0392e73b6d2b0ac3308466b49d608aa840",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "7bf38fea_2f814969",
        "filename": "tests/__cxa_thread_atexit_test.cpp",
        "patchSetId": 5
      },
      "lineNbr": 57,
      "author": {
        "id": 1003224
      },
      "writtenOn": "2015-11-30T19:02:37Z",
      "side": 1,
      "message": "(this fails to link.)",
      "parentUuid": "9b0923b2_c8698fa2",
      "revId": "6a12eb0392e73b6d2b0ac3308466b49d608aa840",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "bbe987fc_1a000143",
        "filename": "tests/__cxa_thread_atexit_test.cpp",
        "patchSetId": 5
      },
      "lineNbr": 57,
      "author": {
        "id": 1041673
      },
      "writtenOn": "2015-12-01T01:13:20Z",
      "side": 1,
      "message": "It fails to link only when we use thread_local; I was thinking along the lines of replacing GTEST_LOG with GTETST_FAIL",
      "parentUuid": "7bf38fea_2f814969",
      "revId": "6a12eb0392e73b6d2b0ac3308466b49d608aa840",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    }
  ]
}