{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "adcb0e5e_bb49f6b0",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1268571
      },
      "writtenOn": "2024-02-08T18:47:33Z",
      "side": 1,
      "message": "not sure how this could cause the test failure, but let\u0027s roll back and investigate.",
      "revId": "c20e1c2bdfc00b3fb7931da5e88ceac3fa4df4b2",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}